"""Initial schema

Revision ID: 095e10abb6f9
Revises: 
Create Date: 2026-03-06 12:36:11.509931
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '095e10abb6f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('name', name=op.f('uq_stores_name'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_categories_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('store_id', 'name', name='uq_categories_store_id_name')
    )
    op.create_index('ix_categories_normalized_name', 'categories', ['normalized_name'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('run_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categories_processed', sa.Integer(), nullable=False),
    sa.Column('products_processed', sa.Integer(), nullable=False),
    sa.Column('products_created', sa.Integer(), nullable=False),
    sa.Column('products_updated', sa.Integer(), nullable=False),
    sa.Column('price_changes_detected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_scrape_runs_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_index('ix_scrape_runs_started_at', 'scrape_runs', ['started_at'], unique=False)
    op.create_table('category_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_category_id', sa.Integer(), nullable=False),
    sa.Column('target_category_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_category_id'], ['categories.id'], name=op.f('fk_category_mappings_reference_category_id_categories')),
    sa.ForeignKeyConstraint(['target_category_id'], ['categories.id'], name=op.f('fk_category_mappings_target_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_mappings')),
    sa.UniqueConstraint('reference_category_id', 'target_category_id', name='uq_category_mappings_pair')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('normalized_name', sa.String(length=1000), nullable=True),
    sa.Column('name_hash', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_url', sa.String(length=2000), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], name=op.f('fk_products_scrape_run_id_scrape_runs')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_products_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('store_id', 'product_url', name='uq_products_store_id_product_url')
    )
    op.create_index('ix_products_name_hash', 'products', ['name_hash'], unique=False)
    op.create_index('ix_products_normalized_name', 'products', ['normalized_name'], unique=False)
    op.create_index('ix_products_scraped_at', 'products', ['scraped_at'], unique=False)
    op.create_table('product_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_product_id', sa.Integer(), nullable=False),
    sa.Column('target_product_id', sa.Integer(), nullable=False),
    sa.Column('match_status', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_product_id'], ['products.id'], name=op.f('fk_product_mappings_reference_product_id_products')),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], name=op.f('fk_product_mappings_target_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_mappings')),
    sa.UniqueConstraint('reference_product_id', 'target_product_id', name='uq_product_mappings_pair')
    )
    op.create_table('product_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_price_history_product_id_products')),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], name=op.f('fk_product_price_history_scrape_run_id_scrape_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_price_history'))
    )
    op.create_index('ix_price_history_product_id', 'product_price_history', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_history_product_id', table_name='product_price_history')
    op.drop_table('product_price_history')
    op.drop_table('product_mappings')
    op.drop_index('ix_products_scraped_at', table_name='products')
    op.drop_index('ix_products_normalized_name', table_name='products')
    op.drop_index('ix_products_name_hash', table_name='products')
    op.drop_table('products')
    op.drop_table('category_mappings')
    op.drop_index('ix_scrape_runs_started_at', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_categories_normalized_name', table_name='categories')
    op.drop_table('categories')
    op.drop_table('stores')
    # ### end Alembic commands ###
